// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Embroidr.UI {
    
    
    public partial class MainWindow {
        
        private Gtk.Action FileAction;
        
        private Gtk.Action findAction;
        
        private Gtk.Action FindAction;
        
        private Gtk.Action saveAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar2;
        
        private Gtk.Toolbar toolbar3;
        
        private Gtk.HPaned hpaned2;
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TreeView treeview1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.NodeView nodeview1;
        
        private Gtk.Statusbar statusbar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Embroidr.UI.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
            this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
            w2.Add(this.FileAction, null);
            this.findAction = new Gtk.Action("findAction", null, null, "gtk-find");
            w2.Add(this.findAction, null);
            this.FindAction = new Gtk.Action("FindAction", Mono.Unix.Catalog.GetString("Find"), null, null);
            this.FindAction.ShortLabel = Mono.Unix.Catalog.GetString("Find");
            w2.Add(this.FindAction, null);
            this.saveAction = new Gtk.Action("saveAction", null, null, "gtk-save");
            w2.Add(this.saveAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "Embroidr.UI.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("Embroidr");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "stock_insert_special_character", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(2));
            // Container child Embroidr.UI.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar2'><menu action='FileAction'><menuitem action='FindAction'/></menu></menubar></ui>");
            this.menubar2 = ((Gtk.MenuBar)(w1.GetWidget("/menubar2")));
            this.menubar2.Name = "menubar2";
            this.vbox1.Add(this.menubar2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><toolbar name='toolbar3'><toolitem action='findAction'/><toolitem action='saveAction'/></toolbar></ui>");
            this.toolbar3 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar3")));
            this.toolbar3.Name = "toolbar3";
            this.toolbar3.ShowArrow = false;
            this.toolbar3.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
            this.vbox1.Add(this.toolbar3);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.toolbar3]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hpaned2 = new Gtk.HPaned();
            this.hpaned2.CanFocus = true;
            this.hpaned2.Name = "hpaned2";
            this.hpaned2.Position = 160;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.treeview1 = new Gtk.TreeView();
            this.treeview1.CanFocus = true;
            this.treeview1.Name = "treeview1";
            this.treeview1.HeadersClickable = true;
            this.GtkScrolledWindow1.Add(this.treeview1);
            this.vbox2.Add(this.GtkScrolledWindow1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
            w6.Position = 0;
            this.hpaned2.Add(this.vbox2);
            Gtk.Paned.PanedChild w7 = ((Gtk.Paned.PanedChild)(this.hpaned2[this.vbox2]));
            w7.Resize = false;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.nodeview1 = new Gtk.NodeView();
            this.nodeview1.CanFocus = true;
            this.nodeview1.Name = "nodeview1";
            this.nodeview1.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.nodeview1);
            this.hpaned2.Add(this.GtkScrolledWindow);
            this.vbox1.Add(this.hpaned2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox1[this.hpaned2]));
            w10.Position = 2;
            // Container child vbox1.Gtk.Box+BoxChild
            this.statusbar1 = new Gtk.Statusbar();
            this.statusbar1.Name = "statusbar1";
            this.statusbar1.Spacing = 6;
            this.vbox1.Add(this.statusbar1);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
            w11.Position = 3;
            w11.Expand = false;
            w11.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 699;
            this.DefaultHeight = 638;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.findAction.Activated += new System.EventHandler(this.OnFindActionActivated);
            this.saveAction.Activated += new System.EventHandler(this.OnSaveActionActivated);
        }
    }
}
